name: firebase_admin_interop
description: Firebase Admin SDK for Dart written as a wrapper around official Node.js SDK.
version: 2.1.0
homepage: https://github.com/pulyaevskiy/firebase-admin-interop
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3
  node_interop:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./node_interop/
      ref: feature/update-dependencies
  meta: ^1.3.0
  quiver: ^3.0.0

dev_dependencies:
  test: ^1.16.8
  build_runner: ^1.12.2
  build_node_compilers:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./build_node_compilers/
      ref: feature/update-dependencies
  build_test: ^2.0.0
  node_http:
    git:
      url: https://github.com/blaueeiner/node-interop
      path: ./node_http/
      ref: feature/update-dependencies
